### ISSUE TITLE
Regarding Shared Component Styling...

### ISSUE THREAD

**Issue by steve-a-jones** [styled-components/styled-components-experimentation#1]
Just finished reading https://github.com/styled-components/styled-components-experimentation/blob/master/component-libraries/shared-component-libraries.md

This pattern seems flexible enough to solve most theme isolation/namespacing issues - I will definitely give this a try.

Question:
It appears that in order for default styling to be applied the consumer will always need to use the exported ThemeProvider (since this is where to the default styling gets applied). 

With this pattern - if the consumer were to simply import the raw styled-component `props.theme` would not exist.

Curious if you have put any more thought into this pattern and propose a (slightly) more elegant solution for applying default styling out of box without concerning consumers with ThemeProvider unless they need to perform overrides.

**Comment by mxstbr** [comment]
Define the default props like with any other React component!

```JS
const LibraryButton = styled.button`
  background: ${props => props.theme.bg};
`

LibraryButton.defaultProps = {
  theme: {
    bg: 'red'
  }
}
```

**Comment by steve-a-jones** [comment]
🥇 Legit. Thank you!
